GET http://localhost:5000/ HTTP/1.1

####

POST http://localhost:5000/hello HTTP/1.1
Content-Type: application/json

{
  "name":"toto"
}

####

POST http://localhost:5000/formation HTTP/1.1
Content-Type: application/json

{
  "nom":"toto",
  "salle":"tata"
}

####

POST http://localhost:5000/alchemy/formation HTTP/1.1
Content-Type: application/json

{
  "name":"fromalchemy",
  "room":"fromalchemy"
}

#### 

GET http://localhost:5000/alchemy/formation_pg HTTP/1.1